services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: "host"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 784:784/udp
      - 853:853/tcp
      - 3001:3000/tcp
      - 3080:80/tcp
#       - 443:443/tcp
    volumes:
      - /Apps/AdguardHome/work:/opt/adguardhome/work
      - /Apps/AdguardHome/conf:/opt/adguardhome/conf
    restart: unless-stopped


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    privileged: true
    ports:
      - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    deploy:
      restart_policy:
        condition: any