services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:v1.9.1'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/satisfactory:/config'
    environment:
      - MAXPLAYERS=6
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G