services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.21.1
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.docker-1.gwebs.ca`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true

volumes:
  portainer_data:
