services:
  overseerr:
    image: sctx/overseerr:1.33.2
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Toronto
    ports:
      - 5055:5055
    volumes:
      - /Apps/Overseerr:/app/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.docker-1.gwebs.ca`)"
      - "traefik.http.routers.overseerr.entrypoints=web"
    networks:
      - traefik_default

  jackett:
    image: linuxserver/jackett:0.22.664
    container_name: jackett
    environment:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /Apps/Jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.docker-1.gwebs.ca`)"
      - "traefik.http.routers.jackett.entrypoints=web"
    networks:
      - traefik_default

  flaresolverr:
    image: flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.docker-1.gwebs.ca`)"
      - "traefik.http.routers.flaresolverr.entrypoints=web"
    networks:
      - traefik_default


  # lidarr:
  #   image: linuxserver/lidarr:latest
  #   container_name: lidarr
  #   environment:
  #     - PUID=950
  #     - PGID=950
  #     - TZ=America/Toronto
  #   volumes:
  #     - /Apps/Lidarr:/config
  #     - medias:/medias #optional
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped


  radarr:
    image: linuxserver/radarr:5.10.4
    container_name: radarr
    environment:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
    volumes:
      - /Apps/Radarr:/config
      - medias:/medias
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.docker-1.gwebs.ca`)"
      - "traefik.http.routers.radarr.entrypoints=web"
    networks:
      - traefik_default

  sonarr:
    image: linuxserver/sonarr:4.0.9
    container_name: sonarr
    environment:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
    volumes:
      - /Apps/Sonarr:/config
      - medias:/medias
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.docker-1.gwebs.ca`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
    networks:
      - traefik_default

  transmission-openvpn:
    container_name: transmission-ovpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - medias:/medias
    environment:
      - LOCAL_NETWORK=192.168.10.0/24,100.64.0.0/10
      - TRANSMISSION_SPEED_LIMIT_UP=0
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=9999
      - TRANSMISSION_MAX_PEER_GLOBAL=99999
      - TRANSMISSION_PEER_LIMIT_GLOBAL=9999
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=9999
      - TRANSMISSION_DOWNLOAD_DIR=/medias/Torrent
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_WEB_UI=transmission-web-control
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - '9091:9091'
    image: haugene/transmission-openvpn:5.3
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.docker-1.gwebs.ca`)"
      - "traefik.http.routers.transmission.entrypoints=web"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true


volumes:
    medias:
      driver: local
      driver_opts:
        type: cifs
        device: //192.168.10.12/Medias
        o: username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=950,gid=950
