version: "3.8"
services:
  plex:
    image: linuxserver/plex:1.30.0
    container_name: plex
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PUID=950
      - PGID=950
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /mnt/Vault/Apps/Plex:/config
      - /mnt/Vault/Medias:/Plex
    restart: unless-stopped
    
  overseerr:
    image: sctx/overseerr:1.31.0
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Toronto
    ports:
      - 5055:5055
    volumes:
      - /mnt/Vault/Apps/Overseerr:/app/config
    restart: unless-stopped
    
  jackett:
    image: linuxserver/jackett:0.20.2309
    container_name: jackett
    environment:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /mnt/Vault/Apps/Jackett:/config
      - /mnt/Vault/Medias/Torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:4.2.4
    container_name: radarr
    environment:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
    volumes:
      - /mnt/Vault/Apps/Radarr:/config
      - /mnt/Vault/Medias/Movies:/medias/Movies
      - /mnt/Vault/Medias/Torrent:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:3.0.9
    container_name: sonarr
    environment:
      - PUID=950
      - PGID=950
      - TZ=America/Toronto
    volumes:
      - /mnt/Vault/Apps/Sonarr:/config
      - /mnt/Vault/Medias/Animes:/medias/Animes
      - /mnt/Vault/Medias/TV:/medias/TV
      - /mnt/Vault/Medias/Torrent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  transmission-openvpn:
    container_name: transmission-ovpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/Vault/Medias/Torrent:/downloads
    env_file:
      - env_file
    environment:
      - LOCAL_NETWORK=192.168.10.0/24
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5
      - TRANSMISSION_MAX_PEER_GLOBAL=99999
      - TRANSMISSION_PEER_LIMIT_GLOBAL=9999
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=9999
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_WEB_UI=transmission-web-control
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - '9091:9091'
    image: haugene/transmission-openvpn:4.0
    restart: unless-stopped
