services:
  plex:
    image: linuxserver/plex:1.40.1
    container_name: plex
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PUID=950
      - PGID=950
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /Apps/Plex:/config
      - medias:/Plex
    restart: unless-stopped

volumes:
    medias:
      driver: local
      driver_opts:
        type: cifs
        device: //192.168.10.12/Medias
        o: username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=950,gid=950
