services:
  plex:
    image: linuxserver/plex:1.41.0
    container_name: plex
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PUID=950
      - PGID=950
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /Apps/Plex:/config
      - medias:/Plex
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    privileged: true
    ports:
      - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    deploy:
      restart_policy:
        condition: any

volumes:
    medias:
      driver: local
      driver_opts:
        type: cifs
        device: //192.168.10.12/Medias
        o: username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=950,gid=950
