version: "2.1"
services:
  tailscale:
    container_name: tailscale
    build: .
    env_file:
      - env_file
    volumes:
      # - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
