services:
  stirling-pdf:
    container_name: Stirling-PDF
    image: frooodle/s-pdf:0.45.0
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -qv 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - 8085:8080
    # volumes:
    #   - /stirling/latest/data:/usr/share/tesseract-ocr/5/tessdata:rw
    #   - /stirling/latest/config:/configs:rw
    #   - /stirling/latest/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      SECURITY_ENABLELOGIN: "false"
      SYSTEM_DEFAULTLOCALE: fr_FR
      UI_APPNAME: Stirling-PDF
      UI_HOMEDESCRIPTION: Stirling-PDF
      UI_APPNAMENAVBAR: Stirling-PDF
      # SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      # SYSTEM_GOOGLEVISIBILITY: "true"
      restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdf.rule=Host(`pdf.docker-1.gwebs.ca`) ||Host(`pdf.docker-2.gwebs.ca`) "
      - "traefik.http.routers.pdf.entrypoints=web"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true