services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3055:8080"
    # environment:
    #   - OPENAI_API_KEY=your_secret_key
    volumes:
      - /Apps/open-webui/:/app/backend/data
    restart: always