services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
#    ports:
#      - "3055:8080"
    # environment:
    #   - OPENAI_API_KEY=your_secret_key
    volumes:
      - /Apps/open-webui/:/app/backend/data
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai.rule=Host(`ai.docker-1.gwebs.ca`)"
      - "traefik.http.routers.ai.entrypoints=web"
      - "traefik.http.services.ai.loadbalancer.server.port=8080"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true