# Tasks/docker.yml

- name: Create application directory for {{ application }}
  ansible.builtin.file:
    path: /home/gabriel/{{ application }}
    state: directory

- name: Copy application folder for {{ application }} only if different
  ansible.builtin.copy:
    src: ../Docker/{{ application }}/
    dest: /home/gabriel/{{ application }}
    decrypt: true
    mode: preserve
    force: true  # Only overwrites if changed
    remote_src: no

- name: Build docker compose command for {{ application }}
  ansible.builtin.set_fact:
    docker_compose_command: >-
      docker compose up -d
      {% if (restart | default(false)) | bool %} --force-recreate{% endif %}
      {% if (pull_latest | default(false)) | bool %} --pull always{% endif %}

- name: Print docker compose command for {{ application }}
  ansible.builtin.debug:
    msg: "{{ docker_compose_command }}"

- name: Run docker-compose up asynchronously for {{ application }}
  ansible.builtin.command: "{{ docker_compose_command }}"
  args:
    chdir: /home/gabriel/{{ application }}/
  async: 300
  poll: 0
  register: compose_async

- name: Wait for docker-compose up to finish for {{ application }}
  ansible.builtin.async_status:
    jid: "{{ compose_async.ansible_job_id }}"
  register: async_poll
  until: async_poll.finished
  retries: 10
  delay: 5
  when: compose_async.ansible_job_id is defined