- name: Skip if host is unreachable
  meta: end_host
  when: inventory_hostname not in ansible_play_hosts

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_installed
  ignore_errors: true

- name: Download Docker installation script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  when: docker_installed.rc != 0

- name: Run Docker installation script
  ansible.builtin.command: sh /tmp/get-docker.sh
  when: docker_installed.rc != 0

- name: Create application directory for {{ application }}
  ansible.builtin.file:
    path: /home/gabriel/{{ application }}
    state: directory

- name: Copy application folder for {{ application }}
  ansible.builtin.copy:
    src: ../Docker/{{ application }}/
    dest: /home/gabriel/{{ application }}
    decrypt: true

- name: Build docker compose command for {{ application }}
  ansible.builtin.set_fact:
    docker_compose_command: >-
      docker compose up -d
      {% if (restart | default(false)) | bool %} --force-recreate{% endif %}
      {% if (pull_latest | default(false)) | bool %} --pull always{% endif %}

- name: Print docker compose command for {{ application }}
  ansible.builtin.debug:
    msg: "{{ docker_compose_command }}"

- name: Run docker-compose up -d for {{ application }}
  ansible.builtin.command: "{{ docker_compose_command }}"
  args:
    chdir: /home/gabriel/{{ application }}/
