- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: yes

- name: Download Docker installation script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  when: docker_installed.rc != 0

- name: Run Docker installation script
  ansible.builtin.shell: sh /tmp/get-docker.sh
  when: docker_installed.rc != 0

- name: Create application directory for {{ application }}
  file:
    path: /home/gabriel/{{ application }}
    state: directory

- name: Copy application folder for {{ application }}
  ansible.builtin.copy:
    src: ../Docker/{{ application }}/
    dest: /home/gabriel/{{ application }}
    decrypt: yes

- name: Run docker-compose up -d for {{ application }}
  ansible.builtin.shell: >
    docker compose up -d
    {% if restart | default(false) %}
    --force-recreate
    {% endif %}
  args:
    chdir: /home/gabriel/{{ application }}/