# Tasks/install_docker.yml

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_installed
  ignore_errors: true

- name: Download Docker installation script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  when: docker_installed.rc != 0

- name: Run Docker installation script
  ansible.builtin.command: sh /tmp/get-docker.sh
  when: docker_installed.rc != 0