version: "2.1"
services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks
    container_name: healthchecks
    env_file:
      - env_file
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=http://10.10.0.8:9500
      - SITE_NAME=HealthChecks
      # - DEFAULT_FROM_EMAIL=<DEFAULT_FROM_EMAIL>
      # - EMAIL_HOST=<EMAIL_HOST>
      # - EMAIL_PORT=<EMAIL_PORT>
      # - EMAIL_HOST_USER=<EMAIL_HOST_USER>
      # - EMAIL_HOST_PASSWORD=<EMAIL_HOST_PASSWORD>
      # - EMAIL_USE_TLS=<True or False>
      # - SUPERUSER_EMAIL=
      # - SUPERUSER_PASSWORD=
      - REGENERATE_SETTINGS=False #optional
      # - SITE_LOGO_URL=<SITE_LOGO_URL> #optional
      # - ALLOWED_HOSTS=<ALLOWED_HOSTS> #optional
      # - SECRET_KEY=<SECRET_KEY> #optional
      # - APPRISE_ENABLED=True/False #optional
    volumes:
      - /mnt/Vault/Apps/Healthchecks:/config
    ports:
      - 9500:8000
    restart: unless-stopped