services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:v2.2.1-ls129
    container_name: healthchecks
    env_file:
      - env_file
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=http://10.10.0.8:9500
      - SITE_NAME=Healthchecks.local
      # - DEFAULT_FROM_EMAIL=<DEFAULT_FROM_EMAIL>
      # - EMAIL_HOST=<EMAIL_HOST>
      # - EMAIL_PORT=<EMAIL_PORT>
      # - EMAIL_HOST_USER=<EMAIL_HOST_USER>
      # - EMAIL_HOST_PASSWORD=<EMAIL_HOST_PASSWORD>
      # - EMAIL_USE_TLS=<True or False>
      # - SUPERUSER_EMAIL=
      # - SUPERUSER_PASSWORD=
      - REGENERATE_SETTINGS=False #optional
      - SITE_LOGO_URL=https://pbs.twimg.com/profile_images/1055543716201615365/geMDWaHV_400x400.jpg
      # - ALLOWED_HOSTS=<ALLOWED_HOSTS> #optional
      # - SECRET_KEY=<SECRET_KEY> #optional
      # - APPRISE_ENABLED=True/False #optional
    volumes:
      - /Apps/Healthchecks:/config
    ports:
      - 9500:8000
    restart: unless-stopped
