services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD} #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
      # - PWA_APPNAME=code-server #optional
    volumes:
      - /Apps/code-server:/config
    restart: unless-stopped


    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`code.docker-1.gwebs.ca`)"
      - "traefik.http.routers.code.entrypoints=websecure"
      - "traefik.http.routers.code.tls=true"
      - "traefik.http.routers.code.tls.certresolver=le"
      - "traefik.http.routers.code-insecure.rule=Host(`code.docker-1.gwebs.ca`)"
      - "traefik.http.routers.code-insecure.entrypoints=web"
      - "traefik.http.routers.code-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.code.loadbalancer.server.port=8443"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true