services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:v0.8.1-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8085:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /Apps/Scrutiny/config:/opt/scrutiny/config
      - /Apps/Scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
    restart: unless-stopped