- hosts: localhost
  connection: localhost
  order: sorted
  tasks:
    - name: Copy plexapps secret file and decrypt
      copy:
        src: ../Docker/plexapps/env_file.vault
        dest: ../Docker/plexapps/env_file
        decrypt: yes

    - name: Copy healthchecks secret file and decrypt
      copy:
        src: ../Docker/healthchecks/env_file.vault
        dest: ../Docker/healthchecks/env_file
        decrypt: yes

    # - name: Copy tailscale secret file and decrypt
    #   copy:
    #     src: ../Docker/tailscale/env_file.vault
    #     dest: ../Docker/tailscale/env_file
    #     decrypt: yes
