- name: AdguardHome
  hosts: DNS-2
  become: true
  vars:
    application: "adguardhome"
  tasks:
    - name: Include Docker tasks
      ansible.builtin.include_tasks: ./Tasks/docker.yml

- name: Heimdall
  hosts: Docker-2
  become: true
  vars:
    application: "heimdall"
  tasks:
    - name: Include Docker tasks
      ansible.builtin.include_tasks: ./Tasks/docker.yml

- name: Pdf
  hosts: Docker-2
  become: true
  vars:
    application: "pdf"
  tasks:
    - name: Include Docker tasks
      ansible.builtin.include_tasks: ./Tasks/docker.yml

- name: HomeAssistant
  hosts: Docker-2
  become: true
  vars:
    application: "homeassistant"
  tasks:
    - name: Include Docker tasks
      ansible.builtin.include_tasks: ./Tasks/docker.yml

- name: Portainer
  hosts: Docker-2
  become: true
  vars:
    application: "portainer"
  tasks:
    - name: Include Docker tasks
      ansible.builtin.include_tasks: ./Tasks/docker.yml

- name: Upsnap
  hosts: Docker-2
  become: true
  vars:
    application: "upsnap"
  tasks:
    - name: Include Docker tasks
      ansible.builtin.include_tasks: ./Tasks/docker.yml
