- name: Deploy Docker Applications
  hosts: all
  become: true
  strategy: free
  tasks:
    - name: Deploy Traefik
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "traefik"
      when: inventory_hostname == "Docker-2"

    - name: Deploy AdguardHome
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "adguardhome"
      when: inventory_hostname == "DNS-2"

    - name: Deploy Heimdall
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "heimdall"
      when: inventory_hostname == "Docker-2"

    - name: Deploy HomePage
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "homepage"
        restart: true
      when: inventory_hostname == "Docker-2"

    - name: Deploy Pdf
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "pdf"
      when: inventory_hostname == "Docker-2"

    - name: Deploy HomeAssistant
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "homeassistant"
      when: inventory_hostname == "Docker-2"

    - name: Deploy Portainer
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "portainer"
      when: inventory_hostname == "Docker-2"

    - name: Deploy Upsnap
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      vars:
        application: "upsnap"
      when: inventory_hostname == "Docker-2"
