- name: Deploy Docker Applications for PVE-2
  hosts: all
  become: true
  vars:
    docker_apps_by_host:
      Docker-2:
        - { name: traefik }
        - { name: heimdall }
        - { name: homepage-2, restart: true }
        - { name: pdf }
        - { name: homeassistant }
        - { name: portainer }
        - { name: upsnap }
      DNS-2:
        - { name: adguardhome }
  tasks:
    - name: Deploy docker apps for each host on PVE-2
      ansible.builtin.include_tasks: ./Tasks/docker.yml
      loop: "{{ docker_apps_by_host[inventory_hostname] | default([]) }}"
      loop_control:
        loop_var: item
      vars:
        application: "{{ item.name }}"
        restart: "{{ item.restart | default(omit) }}"
        pull_latest: "{{ item.pull_latest | default(omit) }}"