- hosts: Plex-1
  order: sorted
  become: true

  tasks:
    - name: Install nvidia-headless-565-server
      apt:
        name: nvidia-headless-565-server
        state: present

    - name: Install nvidia-utils-565-server
      apt:
        name: nvidia-utils-565-server
        state: present

    - name: Install libnvidia-encode-565-server
      apt:
        name: libnvidia-encode-565-server
        state: present