- name: AdguardHome
  hosts: DNS-2
  become: yes
  vars:
    application: "adguardhome"
  tasks:
    - include_tasks: ./Tasks/docker.yml

- name: Heimdall
  hosts: Docker-2
  become: yes
  vars:
    application: "heimdall"
  tasks:
    - include_tasks: ./Tasks/docker.yml

- name: pdf
  hosts: Docker-2
  become: yes
  vars:
    application: "pdf"
  tasks:
    - include_tasks: ./Tasks/docker.yml

- name: Portainer
  hosts: Docker-2
  become: yes
  vars:
    application: "portainer"
  tasks:
    - include_tasks: ./Tasks/docker.yml
