- hosts: NAS-1
  order: sorted
  become: true

  tasks:

    - name: Install ACL
      apt:
        name: acl
        state: present

    - name: Install Samba
      apt:
        name: samba
        state: present

    - name: Install Sanoid
      apt:
        name: sanoid
        state: present

    - name: Install Rclone
      apt:
        name: rclone
        state: present

    - name: Install Smartmontools
      apt:
        name: smartmontools
        state: present

    - name: Ensure /etc/sanoid directory exists
      file:
        path: /etc/sanoid
        state: directory

    - name: Copy sanoid.conf
      copy:
        src: ../etc/sanoid/sanoid.conf
        dest: /etc/sanoid/sanoid.conf

    - name: Enable and start sanoid.timer
      systemd:
        name: sanoid.timer
        enabled: yes
        state: started        

    - name: Copy smb.conf
      copy:
        src: ../etc/samba/smb.conf
        dest: /etc/samba/smb.conf

