---
- name: Update Ubuntu servers
  hosts: linux_vms
  become: true  # To escalate privileges using sudo
  gather_facts: true  # To gather facts about the hosts

  tasks:
    - name: Update ansible.builtin.apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true
