- name: Update Ubuntu servers
  hosts: linux_vms
  become: true
  gather_facts: true
  strategy: free
  ignore_unreachable: true       # <--- Add this line
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true

    - name: Check if docker is installed
      ansible.builtin.stat:
        path: /usr/bin/docker
      register: docker_stat

    - name: Run 'docker system prune -a'
      ansible.builtin.command: docker system prune -af
      when: docker_stat.stat.exists
      # become: true # Uncomment if needed