# IP Address Pool for LAN 1 (192.168.10.0/24)
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan1-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.25-192.168.10.25
  autoAssign: false
---
# IP Address Pool for LAN 2 (192.168.15.0/24)
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan2-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.15.25-192.168.15.25
  autoAssign: false
---
# L2 Advertisement for LAN 1
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan1-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - lan1-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-1  # Only advertise on worker-1
---
# L2 Advertisement for LAN 2
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - lan2-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: k8s-worker-2  # Only advertise on worker-2
