services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.6.3
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /Apps/Heimdall:/config
    ports:
      - 85:80
#       - 443:443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.docker-1.gwebs.ca`) || Host(`heimdall.docker-2.gwebs.ca`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls=true"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true