services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.6.3
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /Apps/Heimdall:/config
    ports:
      - 85:80
#       - 443:443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.docker-1.gwebs.ca`) || Host(`heimdall.docker-2.gwebs.ca`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.tls.certresolver=le"
      - "traefik.http.routers.heimdall.tls.domains[0].main=docker-1.gwebs.ca"
      - "traefik.http.routers.heimdall.tls.domains[0].sans=*.docker-1.gwebs.ca"
      - "traefik.http.routers.heimdall.tls.domains[1].main=docker-2.gwebs.ca"
      - "traefik.http.routers.heimdall.tls.domains[1].sans=*.docker-2.gwebs.ca"
      - "traefik.http.routers.heimdall-secure.service=heimdall"
      - "traefik.http.routers.heimdall-insecure.rule=Host(`heimdall.docker-1.gwebs.ca`) || Host(`heimdall.docker-2.gwebs.ca`)"
      - "traefik.http.routers.heimdall-insecure.entrypoints=web"
      - "traefik.http.routers.heimdall-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true