services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /Apps/HomeAssistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.heimdall.rule=Host(`homeassistant.docker-1.gwebs.ca`)"
    #   - "traefik.http.routers.heimdall.entrypoints=web"